### ISSUE TITLE
Stop mousemove in same territory from interrupting animation

### ISSUE THREAD

**Issue by rmcarder** [EAPTSD/EAP-Map#7]
If slowly moving mouse continuously, animations on the sidebar are interrupted by the new mousemove query, even if the mouse is in the same region.

**Comment by ostermanj** [comment]
Hey, Rich. I have a commit coming soon that should take care of that. Fires mousemove events only if the region is different from he last. Will push soon.

**Comment by rmcarder** [comment]
Awesome!

**Comment by ostermanj** [comment]
Just pushed commit 41630c2 to master which limits the mousemove event to when it's different from the last. It also adds a right click to hold selection so that ppl can select a region and move the mouse to do other things without selecting other regions.

A couple issues came up: admin level 1 names aren't necessarily unique so I need to figure out how to uniquely identify each. I think the properties have country fip and county fip as separate fields, so it's harder to have mapBox filter on the concatenation of both. I think the new expressions method may be able to handle it. I'll investigate that later.

**Comment by ostermanj** [comment]
Actually I think the problem is not with admin level 1 name's being nonunique, but something else in the data where non-Mongolian provinces are showing as if they are part of Mongolia. Will create new issue.
